### PR TITLE
2357 add junctions to suburban widgets

### PR DESCRIPTION
**Pull request by ziv17**
The previous PR was closed by mistake. Opening a new one.

### CODE REVIEW

**Comment by atalyaalon** [comment]
@ziv17 Following [the correspondence here](https://github.com/data-for-change/anyway/pull/2397) you can find a road segment table (As to 03-2022) [here](https://docs.google.com/spreadsheets/d/1bhP5cqMG0NYtRiE1MVMMpzZTTLY5D9iM/edit?usp=sharing&ouid=107504073445238825008&rtpof=true&sd=true).

I waiting for a new updated of that table, hope to get it soon. For now you can make sure to create a csv and adjust our [parser code](https://github.com/data-for-change/anyway/blob/dev/anyway/parsers/road_segments.py) AND make sure loading works as expected. Let me know if you find additional errors as the one you found and I'll send the new segments table ASAP

**Comment by atalyaalon** [comment]
Also @ziv17 can we create tests that use GPS data of junctions (we have this data from the CBS) and use segments GPS and maybe even data from google maps Geocoding to find errors?

**Comment by ziv17** [comment]
Hi @atalyaalon ,
I am not sure how to handle discrepancies like the following:
Accidents in suburban junction 4193 (road=1, מחלף דניאל) report it is on km 22 (see query below)
Road segment 10054 starts at km: 22.9
I did not find the road segment that ends there.

query:
select road1, non_urban_intersection , km, km_accurate, accident_timestamp from markers_hebrew where non_urban_intersection=4193 order by accident_timestamp

**Comment by ziv17** [comment]
Hi @atalyaalon ,
I am not sure how to handle discrepancies like the following:
Accidents in suburban junction 4193 (road=1, מחלף דניאל) report it is on km 22 (see query below)
Road segment 10054 starts at km: 22.9
I did not find the road segment that ends there.

query:
select road1, non_urban_intersection , km, km_accurate, accident_timestamp from markers_hebrew where non_urban_intersection=4193 order by accident_timestamp

**Comment by ziv17** [comment]
Hi @atalyaalon 
In essence, this PR adds `OR suburban_junction in ( <juncltion list> )` to widget queries that has the `segment_id` field in the filter. It is finally ready.

**Comment by atalyaalon** [comment]
@ziv17 , this pr looks great! Awesome work!
I want to merge ASAP.
A few questions right before merging:

1. I assume once merged we should load all of the CBS Data from past years to make sure the RoadJunctionKM tables are filled?
2. Should we add non_urban_intersection index to relevant tables that use get_query (say markers_hebrew) to make sure cache fill runs in a reasonable time?
3. Besides get_query, do we have other calls in our code of infographics widgets we need to adjust? (We can open separate issues for them and merge this one)
4. TODOs in code: 
- TODO of implementation of top_road_segments_accidents_per_km_widget - perhaps you can open a separate issue?
- TODO of remove road_segment_name if road_segment_id exists: I saw you have a draft pr. I assume it would be the next pr we'll merge?

**Comment by ziv17** [comment]
>     1. I assume once merged we should load all of the CBS Data from past years to make sure the RoadJunctionKM tables are filled?

Yes, correct

>     2. Should we add non_urban_intersection index to relevant tables that use get_query (say markers_hebrew) to make sure cache fill runs in a reasonable time?

Yes

 
>     3. Besides get_query, do we have other calls in our code of infographics widgets we need to adjust? (We can open separate issues for them and merge this one)

If there are widgets that do not use get_query(), then yes. I can take it as a task if you want.
 
>     4. TODOs in code:
> 
> 
>     * TODO of implementation of top_road_segments_accidents_per_km_widget - perhaps you can open a separate issue?

 Improve implementation: db filter of string not equal and included in list [#2507](https://github.com/data-for-change/anyway/issues/2507) 

> 
>     * TODO of remove road_segment_name if road_segment_id exists: I saw you have a draft pr. I assume it would be the next pr we'll merge?
 Remove road_segment_name from query if road_segment_id is present. [#2503]

**Comment by ziv17** [comment]
Hi @atalyaalon ,
I incorporated the latest commit in dev, and the tests fail on
```
def parse_html_walla(item_rss, html_soup):
    # For some reason there's html here
    description = BeautifulSoup(item_rss["summary"], features="lxml").text

    author = html_soup.find("div", class_="author").get_text().strip()
    return author, description

```
in line `    author = html_soup.find("div", class_="author").get_text().strip()`
The find returns None, and the `get_text()` fails.
(This code is 2.5 years old). This test does not provide much value, as it only tests that the real data that returns in not empty.
What do you think?

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , I incorporated the latest commit in dev, and the tests fail on
> 
> ```
> def parse_html_walla(item_rss, html_soup):
>     # For some reason there's html here
>     description = BeautifulSoup(item_rss["summary"], features="lxml").text
> 
>     author = html_soup.find("div", class_="author").get_text().strip()
>     return author, description
> ```
> 
> in line ` author = html_soup.find("div", class_="author").get_text().strip()` The find returns None, and the `get_text()` fails. (This code is 2.5 years old). This test does not provide much value, as it only tests that the real data that returns in not empty. What do you think?

@ziv17 In that case you can remove the test

**Comment by atalyaalon** [comment]
> Hi @atalyaalon ,
> 
> > ```
> > 1. I assume once merged we should load all of the CBS Data from past years to make sure the RoadJunctionKM tables are filled?
> > ```
> 
> Yes, correct
> 
> > ```

Great


> > 2. Should we add non_urban_intersection index to relevant tables that use get_query (say markers_hebrew) to make sure cache fill runs in a reasonable time?
> > ```
> 
> Yes
> 
> > ```

Great, can you create a list of the tables and create new migration / add to current DB migration in this pr?
I want to make sure it's added in this PR

> > 3. Besides get_query, do we have other calls in our code of infographics widgets we need to adjust? (We can open separate issues for them and merge this one)
> > ```
> 
> If there are widgets that do not use get_query(), then yes. I can take it as a task if you want.
> 
> > ```

Yes, can you create a list of these widgets in an issue and we'll priorities? (This won't impact current PR, we won't wait)


> > 4. TODOs in code:
> > 
> > 
> > * TODO of implementation of top_road_segments_accidents_per_km_widget - perhaps you can open a separate issue?
> > ```
> 
> Improve implementation: db filter of string not equal and included in list [#2507](https://github.com/data-for-change/anyway/issues/2507)
> 
> > ```
> > * TODO of remove road_segment_name if road_segment_id exists: I saw you have a draft pr. I assume it would be the next pr we'll merge?
> > ```
> 
> Remove road_segment_name from query if road_segment_id is present. [#2503]

**Comment by ziv17** [comment]
> Yes, can you create a list of these widgets in an issue and we'll priorities? (This won't impact current PR, we won't wait)

Opened [2508](https://github.com/data-for-change/anyway/issues/2508)

**Comment by ziv17** [comment]
>  can you create a list of the tables and create new migration / add to current DB migration in this pr?
>I want to make sure it's added in this PR

Will do

**Comment by ziv17** [comment]
Hi @atalyaalon ,
in `anyway/widgets/road_segment_widgets/accident_type_vehicle_type_road_comparison_widget.py` there is a query with road (1 or 2), but no `road_segment`. Should all junctions on these roads be added too?

**Comment by ziv17** [comment]
Below widgets do not use get_query(), and need to be handled specifically.
anyway/widgets/widget_utils.py, get_involved_counts)
anyway/widgets/road_segment_widgets/killed_and_injured_count_per_age_group_widget_utils.py

anyway/widgets/all_locations_widgets/seriously_injured_killed_in_bicycles_scooter_widget.py
anyway/widgets/road_segment_widgets/front_to_side_accidents_by_severity.py
anyway/widgets/road_segment_widgets/killed_and_injured_count_per_age_group_stacked_widget.py
anyway/widgets/road_segment_widgets/killed_and_injured_count_per_age_group_widget.py
anyway/widgets/road_segment_widgets/road2_plus1_widget.py: use `road_segment_id` instead of _name.

**Comment by ziv17** [comment]
Below widgets do not use get_query(), and need to be handled specifically.
anyway/widgets/widget_utils.py, get_involved_counts)
anyway/widgets/road_segment_widgets/killed_and_injured_count_per_age_group_widget_utils.py

anyway/widgets/all_locations_widgets/seriously_injured_killed_in_bicycles_scooter_widget.py
anyway/widgets/road_segment_widgets/front_to_side_accidents_by_severity.py
anyway/widgets/road_segment_widgets/killed_and_injured_count_per_age_group_stacked_widget.py
anyway/widgets/road_segment_widgets/killed_and_injured_count_per_age_group_widget.py
anyway/widgets/road_segment_widgets/road2_plus1_widget.py: use `road_segment_id` instead of _name.

**Comment by ziv17** [comment]
Tables with road_segment_id:
AccidentMarkerView - markers_hebrew - Index exists
InvolvedMarkerView - involved_markers_hebrew - Index exists
VehicleMarkerView - vehicles_markers_hebrew - Need to add

**Comment by ziv17** [comment]
Hi @atalyaalon 
I added the junctions to widgets that I missed, and added `non_urban_intersection` index to `markers_hebrew`, `involved_markers_hebrew`, and `vehicles_markers_hebrew`

**Comment by ziv17** [comment]
Hi @atalyaalon This PR is ready for your review

**Comment by atalyaalon** [comment]
Note: No need to resolve conflicts, I resolved them here: https://github.com/data-for-change/anyway/pull/2527
I'll go over this pr during this week, perform some tests and hopefully we'll merge it in the coming days, well done Ziv.

**Comment by ziv17** [comment]
Closes #2546

**Comment by ziv17** [comment]
Closes #2546

**Pull request merged**
