### PR TITLE
modify register order

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by ziv17** [comment]
Hi @atalyaalon ,
Why was it needed?

**Comment by atalyaalon** [comment]
@ziv17 
Apparently the import order changes the order of the widgets in our API and hence the order of their appearance in the UI.
I preferred having all_locations_widgets first, and no_location_widgets last.

**Comment by ziv17** [comment]
@atalyaalon 
We can have specific order. What is the priority of this?

**Comment by atalyaalon** [comment]
@ziv17 not a priority for now. We'll keep current order with the small modification I made in this pr

**Pull request merged**
