### PR TITLE
connect FE to the repo

### PR DESCRIPTION
**Pull request by Shai2022**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@OriHoch we are trying to build a docker-compose that will contain both our BE (current repo) and our [FE - infographics](https://github.com/data-for-change/anyway-newsflash-infographics) repos (so the BE will be able to debug and see changes in the infographics FE) - this is WIP.
What do you think? Any advice on this one?

@Shai2022 do you have any questions for @OriHoch ?

**Comment by OriHoch** [comment]
looks fine :+1:

**Comment by atalyaalon** [comment]
@OriHoch Thanks!
Seems like tests are an issue - https://github.com/data-for-change/anyway/actions/runs/5900941143/job/16006149649?pr=2450#step:3:7 any thoughts?

**Comment by OriHoch** [comment]
> @OriHoch Thanks! Seems like tests are an issue - https://github.com/data-for-change/anyway/actions/runs/5900941143/job/16006149649?pr=2450#step:3:7 any thoughts?

it tries to build the anyway-newsflash-infographics, so you need to run the `anyway-newsflash-infographics/run.bash` to clone the anyway-newsflash-infographics repo

**Comment by Shai2022** [comment]
> > @OriHoch Thanks! Seems like tests are an issue - https://github.com/data-for-change/anyway/actions/runs/5900941143/job/16006149649?pr=2450#step:3:7 any thoughts?
> 
> it tries to build the anyway-newsflash-infographics, so you need to run the `anyway-newsflash-infographics/run.bash` to clone the anyway-newsflash-infographics repo

@OriHoch I tried and not found any solution of clone the repo as part if the docker compose, one solution that i think is to make infographic subrepo of anyeay

**Comment by OriHoch** [comment]
> > > @OriHoch Thanks! Seems like tests are an issue - https://github.com/data-for-change/anyway/actions/runs/5900941143/job/16006149649?pr=2450#step:3:7 any thoughts?
> > 
> > 
> > it tries to build the anyway-newsflash-infographics, so you need to run the `anyway-newsflash-infographics/run.bash` to clone the anyway-newsflash-infographics repo
> 
> @OriHoch I tried and not found any solution of clone the repo as part if the docker compose, one solution that i think is to make infographic subrepo of anyeay

like i wrote in previous comment - run the 'anyway-newsflash-infographics/run.bash' script before running docker compose, same as you do in development, I assume you will also need to run the sed commands in that script anyway to make it work in the CI

**Comment by Shai2022** [comment]
> > > > @OriHoch Thanks! Seems like tests are an issue - https://github.com/data-for-change/anyway/actions/runs/5900941143/job/16006149649?pr=2450#step:3:7 any thoughts?
> > > 
> > > 
> > > it tries to build the anyway-newsflash-infographics, so you need to run the `anyway-newsflash-infographics/run.bash` to clone the anyway-newsflash-infographics repo
> > 
> > 
> > @OriHoch I tried and not found any solution of clone the repo as part if the docker compose, one solution that i think is to make infographic subrepo of anyeay
> 
> like i wrote in previous comment - run the 'anyway-newsflash-infographics/run.bash' script before running docker compose, same as you do in development, I assume you will also need to run the sed commands in that script anyway to make it work in the CI

Done

**Review by OriHoch — APPROVED** [review]
👍

**Comment by atalyaalon** [comment]
@Shai2022 amazing.
@OriHoch Thank you so much!
@tkalir @ziv17 @BarVolunteering  FYI

**Pull request merged**
